# Generated by Django 4.2.9 on 2024-01-30 10:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Main_post",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
